CHANGELOG.md, acceptance/provision.go, connector/connector.go, connector/connector_test.go
Previously, a resource could not be queried *during* the provision flow.
However, this does not match the behaviour of Manifold's production
stack!
=> Ensure resource can be queried *during* provision

CHANGELOG.md, client.go, client_test.go, generated/provider/client/credential/delete_credentials_id_parameters.go, generated/provider/client/credential/put_credentials_id_parameters.go, generated/provider/client/resource/delete_resources_id_parameters.go, generated/provider/client/resource/patch_resources_id_parameters.go, generated/provider/client/resource/put_resources_id_parameters.go, generated/provider/client/single_sign_on/get_sso_parameters.go
Depending on the url provided, it was possible for an sso or callback
url to have two `//` between path segments instead of one breaking some
web servers.
Also fixes the build by upgrading to the latest greatest swagger :)
=> Remove Double Slash from SSO URL

CHANGELOG.md, README.md, cmd/test.go
I've fixed two small bugs:
- Ensure we always append `/v1` to the provided base url
- Update the readme to include a valid example of how to run the `grafton test` command
=> Always append v1 to url

CHANGELOG.md, cmd/test.go
A backwards incomptabile change was introduced in a previous commit
which would *always* append `/v1` to the url. Instead, this commit makes
it only append `/v1` if the given url does not have a trailing `/v1`
segment.
=> Append `/v1` if not already provided in base url

client.go, client_test.go, errors.go, errors_test.go
Where possible, we now convert errors returned from the generated client
into Grafton errors.
At the same time, I've gone through and added exhaustive tests for the
various different http errors we can encounter.
=> Convert client errors into Grafton Errors

.travis.yml, CHANGELOG.md, Makefile, acceptance/credentials.go, credentials.go, credentials_test.go, glide.lock, glide.yaml
Grafton now validates whether or not the credential names it's receiving
back are valid. They must be valid names in accordance with Shell and
Utilities volume of IEEE Std 1003.1-2001.
A function is also exported for use by client libraries.
=> Validate Credential Names during Testing

CHANGELOG.md, acceptance/credentials.go, acceptance/provision.go, acceptance/resize.go, acceptance/sso.go
As a result of the work done to always return a `grafton.Error` from the
grafton client, the acceptance tests were broken.
I've updated the tests appropriately!
=> Fix acceptance tests; check for correct error

acceptance/sso.go
Previously, we didn't check the status code until the last assertion,
meaning we'd check secondary attributes like Content-Type before we
checked whether or not the response was even in the right ballpark.
=> Check SSO Status Code first

CHANGELOG.md, client.go, client_test.go
The Grafton client now returns a ErrMissingMsg if a message is not
returned sent along with a 200, 201, or 202 request.
This enforces behaviour that was already tested for as a part of the
acceptance suite.
=> Return error if missing message

CHANGELOG.md, acceptance/cleanup.go, acceptance/provision.go, acceptance/resize.go
As a part of continued work inside Manifold's platform, we are beginning
to add rollback and cleanup phases to the provisioning and resize
operations.
During a provision, we may need to delete a resource *before* we
complete the flow (which includes creating a set of credentials). This
was not explicitly tested as a part of Grafton, so we've added a test.
It's also possible for something to wrong after creation of a credential
set has completed, however, this would resemble a normal deprovision
which is already tested.
In the case of resize, it's possible that something could go wrong on
Manifold's side after the resize was successful. At which point,
Manifold would then resize the instance back to the original state.
=> Add cleanup feature and resize teardown tests

CHANGELOG.md, client.go, client_test.go, cmd/test.go, glide.lock, glide.yaml
The Grafton client now differentiates between an error and a message returned  from the provider, a message will be returned if a provider sends a valid message despite whether or not it was an error response.
In addition, the client now takes a `logrus.Entry` struct which will be pushed error logs.
=> Add optional logger to Grafton and differentiate errors from messages

client_test.go
It's common for load balancers and other services to return 500 errors
without any bodies. We don't have any test coverage, so I quickly added
some while I was tracking down another bug.
=> Add tests for 500 Response w/ no body

CHANGELOG.md, client.go, client_test.go
Following the spec, a message is not required for a 201 credential
provision response. I've updated the client and added a test to match
this behaviour.
=> Message is not required for 201 Cred Prov. Resp

CHANGELOG.md, connector/connector_test.go, connector/oauth.go, connector/oauth_test.go
This adds support for a JSON message body in POSTs to Grafton's Connector OAuth create access token route.
This is important because our provider documentation indicates that sending a JSON body for this operation is the correct way to do things.
https://docs.manifold.co/providers#tag/OAuth%2Fpaths%2F~1oauth~1tokens%2Fpost
I also added a couple tests.
Closes manifoldco/engineering#2086
=> Grafton Connector Support for JSON POST to create OAuth Token

CHANGELOG.md, acceptance/provision.go, client.go, client_test.go, generated/provider/models/resource_request.go, specs/provider.yaml
We are expanding our API to allow plans to have user selectable features when specified.
This is an extension to Grafton to allow for that.
Relates manifoldco/engineering#3694
=> Adding support for resource feature selections

client.go
Make sure we return a resource measures response with an empty map when a provider responds with `204 - No Content`
=> Return empty measures for 204 status code

connector/oauth.go, connector/oauth_test.go
Not 200, in both docs and real environment.
https://docs.manifold.co/providers#tag/OAuth%2Fpaths%2F~1oauth~1tokens%2Fpost
=> Create Access Token responds with 201

acceptance/acceptance.go, cmd/test.go
Exit code were reversed due to a misleading variable name. 
It returns 1 when passing instead of 0, and 0 when is failing.
I'm returning -1 now to keep inline with other errors throughout the application:
```
return cli.NewExitError("Error: "+err.Error(), -1)
```
Closes: https://github.com/manifoldco/grafton/issues/66
=> Fix exit code on failure

cmd/serve.go, connector/connector.go
Follow-up work will be done to get the responses up to date and make them more useful
See: manifoldco/engineering#5267
Closes manifoldco/engineering#1554
=> Allow the connector server to be run explicitly

cmd/serve.go, marketplace/marketplace.go, marketplace/primitives/fake_product_data.go, marketplace/routes/resources.go
This adds support for setting Product, Plan, and Region on `serve` and uses them in the provision call.
This also fixes an issue where `v1` was not getting appended to the provider API url if omitted.
=> Serve fixes

connector/oauth.go, connector/oauth_test.go
The route expected the autorization code to be in a `application/x-www-form-urlencoded` content-type. It also had some issue with the order of things which could empty the client_id and client_secret if you provided both a body and an Authorization header.
=> Fix the fake connector oauth/tokens route

.travis.yml
This PR adds coverage report for grafton. Since grafron tests run for Go versions 1.9, 1.10, and 1.11 - I've configured it to only publish the report to codecov for 1.11.
=> Add coverage report for grafton

acceptance/acceptance.go, acceptance/credentials.go, acceptance/rotation.go
Backend for testing manual credential rotation. This will be disabled for now until we add new command line flags.
For https://github.com/manifoldco/engineering/issues/7645 & https://github.com/manifoldco/engineering/issues/7616
=> Add manual rotation tests

.travis.yml, Makefile, README.md, go.mod
This makes sure a previous provider passing grafton will still passes the latest tests.
=> Use go-sample-provider to test grafton

acceptance/acceptance.go, acceptance/credentials.go, acceptance/dsl.go, acceptance/rotation.go, specs/provider.yaml
This PR aligns grafton tests with using credential types (multiple/single) to infer which credential rotation algorithm to use.
Fixes https://github.com/manifoldco/engineering/issues/7646
Fixes https://github.com/manifoldco/engineering/issues/7617
=> fix: clean multiple credential support and rotation tests

acceptance/acceptance.go, acceptance/credentials.go, acceptance/rotation.go, cmd/test.go
Add `credential` flag to grafton. It defaults to `multiple`.
=> Add credential flag to grafton

.travis.yml
Right now travis will trigger deployment multiple times and it will eventually fail.
=> fix: deployment

client.go, client_test.go, errors.go
We handle these errors in marketplace, and trust marketplace to be the source of true errors.
Grafton was logging errors and this generated rollbar events when there wasn't an issue because the error was handled by marketplace.
This PR removes those error logs.
=> Remove Error logging in Grafton

cmd/credentials.go, cmd/credentials_test.go
Using `MANIFOLD_HOSTNAME` and `MANIFOLD_SCHEME` one can point grafton's credentials commands to different API endpoints.
=> feat: allow pointing grafton to different api hostnames

CHANGELOG.md, client.go, client_test.go, go.mod, go.sum
These logs will display some of the basic information we and providers need to be able to debug an integration when live. These logs will make sure to no send sensitive information and only give us the required information to support an integration.
Work is related to manifoldco/engineering#10115
=> Add more logs to grafton when sending requests to a provider API

scripts/release.go
Manifold and promulgate are downloaded locally and are not available in the `$PATH` variable, thus we need to use `./` to call them.
=> Use ./ to run manifold and promulgate since they're local

.github/workflows/go.yml
Github actions do not expose env vars by default.
=> Expose the manifold token so we can release using the CLI

.github/workflows/go.yml, scripts/build.go
We used to remove it with sed, it was omitted when initially converting to mage.
=> Remove prefixed v from the version number

.github/workflows/go.yml
It was running on master before hand, now it should only run when a tag is pushed. It will then create the release as excepted.
=> Change the release condition to run on tag push
