manifoldco/grafton

- .gitignore
- CHANGELOG.md
- README.md
- acceptance/acceptance.go
- acceptance/credentials.go
- acceptance/errmatch.go
- acceptance/provision.go
- acceptance/resize.go
- acceptance/sso.go
- client.go
- cmd/test.go
This PR fixes a number of panics, and makes the output for a few error cases way nicer.
> Fix potpourri

- CHANGELOG.md
- client.go
- client_test.go
They don't have bodies, so they can't have messages!
> Don't require messages on 204 responses

- .github/listbot.md
@jeffandersen can you link the bot here?
> Add changelog to listbot

- Gopkg.lock
- Gopkg.toml
- cmd/credentials.go
It no longer needs to be version locked.
> Updated go-manifold

- CHANGELOG.md
- generated/connector/models/resource.go
- specs/connector.yaml
Follows: https://github.com/manifoldco/marketplace/pull/955
> Add resource label to spec

- specs/provider.yaml
Relates manifoldco/engineering#3749
> Updated naming to be less confusing

- CHANGELOG.md
- acceptance/provision.go
Closes manifoldco/engineering#4796
> Allow for callback in provision with same resource test

- acceptance/credentials.go
- acceptance/provision.go
- connector/connector.go
- connector/connector_test.go
- connector/resources.go
- connector/types.go
- db/db.go
- db/types.go
Updated existing ones, and started a refactor towards the mini marketplace.
Closes manifoldco/engineering#5267
> Implemented remaining connector routes

- client.go
See roundtripper.go in the root of the codebase for where we set the date
> Removed date because we add it in roundtripper

- Makefile
- cmd/credentials.go
- cmd/main.go
- cmd/version.go
- config/config.go
Closes: https://github.com/manifoldco/grafton/issues/81
> Add Grafton version at build time

- .travis.yml
- Makefile
Closes: https://github.com/manifoldco/engineering/issues/3277
> Release grafton using promulgate

- specs/connector.yaml
- specs/provider.yaml
> feat: adding credential rotation APIs

- CHANGELOG.md
- cmd/test.go
Fixes: https://github.com/manifoldco/engineering/issues/7824
> Prevent new-plan to be equal to plan flag

- .travis.yml
- Makefile
Sync the makefile with manifold-cli + removed sample-provider test step for now since it broke deployment.
> fix: deployment

- CHANGELOG.md
- generated/provider/models/resource_request.go
- specs/provider.yaml
This will allow service providers to support advanced platform use cases in the future.
> feat: resource provisioning passes the platform_id

- CHANGELOG.md
- client.go
add new platformID field to the grafton client.
> feat: add platform-id in client

- CHANGELOG.md
- acceptance/credentials.go
- acceptance/provision.go
Adding details on wrong status code checks.
> printing details on error cases

- .dependabot/config.yml
> Add depenadabot config

- .dependabot/config.yml
- .github/auto-approve.yml
Do we want auto merge and auto approve on grafton?
If we do here is what we need to do.
> use auto merge for grafton

- .github/workflows/go.yml
We were using the makefile format with parenthesises where we should have used the bash format without.
> Fix some env vars in the commands

- scripts/build.go
Also changed the name of the zip file, the tag and architecture where reversed.
> Add the zip files into the build directory

- cmd/credentials.go
We added the support for multi-product credentials in connector and deprecated single-products credentials. This changes the way grafton rotates the credentials to ensure that we use this new system instead of the old one.
> Update the credentials rotate command to use the provider ID instead of a product ID

- README.md
These have moved so lets update this!
> fix provider doc links
